(()=>{const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const cursor=document.createElement('div');cursor.className='orb-cursor';document.body.append(cursor);
const orb=document.createElement('div');orb.className='floating-orb';orb.innerHTML='<i></i><b></b>';document.body.append(orb);
const scene=document.createElement('canvas');scene.className='webgl-scene';document.body.prepend(scene);const ctx=scene.getContext('2d');let W,H,tt=0;function resize(){W=scene.width=innerWidth*devicePixelRatio;H=scene.height=innerHeight*devicePixelRatio;scene.style.width=innerWidth+'px';scene.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}resize();addEventListener('resize',resize);function draw(){if(reduce)return;ctx.clearRect(0,0,innerWidth,innerHeight);const s=Math.min(innerWidth,innerHeight),cx=innerWidth*.76,cy=innerHeight*.42+Math.sin(tt*.0007)*18;ctx.save();ctx.translate(cx,cy);ctx.rotate(tt*.00012);for(let i=0;i<18;i++){const a=i*Math.PI*2/18+tt*.00005,r=s*(.07+i*.012);ctx.beginPath();ctx.arc(Math.cos(a)*r,Math.sin(a)*r,2+i*.08,0,Math.PI*2);ctx.fillStyle=i%4===0?'rgba(178,92,28,.22)':'rgba(21,27,78,.13)';ctx.fill()}ctx.strokeStyle='rgba(21,27,78,.12)';ctx.lineWidth=1;for(let r=s*.09;r<s*.27;r+=s*.045){ctx.beginPath();ctx.ellipse(0,0,r,r*.62,tt*.0002,0,Math.PI*2);ctx.stroke()}ctx.restore();tt+=16;requestAnimationFrame(draw)}draw();
if(!reduce){let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY;cursor.classList.add('is-live')});(function loop(){x+=(tx-x)*.14;y+=(ty-y)*.14;cursor.style.transform='translate3d('+x+'px,'+y+'px,0)';requestAnimationFrame(loop)})();addEventListener('pointermove',e=>{const rx=(e.clientY/innerHeight-.5)*-14,ry=(e.clientX/innerWidth-.5)*14;orb.style.transform='translate3d(0,0,0) rotateX('+rx+'deg) rotateY('+ry+'deg)'});}
document.querySelectorAll('a,article,.line-link').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('is-hover'));el.addEventListener('mouseleave',()=>cursor.classList.remove('is-hover'))});
document.querySelectorAll('.work-archive article,.list-item,.terminal').forEach(el=>{el.addEventListener('pointermove',e=>{if(reduce)return;const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.setProperty('--rx',(-y*4)+'deg');el.style.setProperty('--ry',(x*4)+'deg');el.style.setProperty('--mx',((x+.5)*100)+'%');el.style.setProperty('--my',((y+.5)*100)+'%')});el.addEventListener('pointerleave',()=>{el.style.removeProperty('--rx');el.style.removeProperty('--ry')})});
document.querySelectorAll('.site-nav nav a,.line-link,.contact-panel a,.brand').forEach(a=>a.addEventListener('click',e=>{const href=a.getAttribute('href');if(!href||href.startsWith('#')||href.startsWith('mailto:')||a.target==='_blank')return;e.preventDefault();document.body.classList.add('is-leaving');setTimeout(()=>location.href=href,260)}));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('main section,article').forEach(e=>io.observe(e));
addEventListener('scroll',()=>{document.documentElement.style.setProperty('--scroll',scrollY+'px')},{passive:true});
})();